version: '3.8'

services:
  app:
    container_name: app
    build: ./
    volumes:
      - type: bind
        source: ./
        target: /fetish_werewolf/
      - type: volume
        source: target
        target: /fetish_werewolf/target/
    tty: true

volumes:
  target:
    driver: local
